resources:
  - name: banaan_repo
    type: gitRepo
    integration: kiran-docker-subint
    pointer:
      sourceName: mkirank/banaan-ios
      branch: master

jobs:
  - name: test-pipeline-macos
    type: runSh
    steps:
      - IN: banaan_repo
      - TASK: 
          script:
              - pushd $(shipctl get_resource_state "banaan_repo")
              - pwd
              - xcodebuild -version
              - xcodebuild test -project ios-test2/banaan.xcodeproj/ -scheme banaan -destination  'platform=iOS Simulator,name=iPhone 8,OS=11.2'
